version: '3.8'

services:
  server:
    build: .
    command: java -jar app.jar
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres_data: